// @ts-nocheck
import { dynamic } from "fumadocs-mdx/runtime/dynamic";
import * as Config from "../source.config";

const _create = await dynamic<
  typeof Config,
  import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
    // biome-ignore lint/complexity/noBannedTypes: generated by fumadocs.
    DocData: {};
  }
>(
  Config,
  { configPath: "source.config.ts", environment: "next", outDir: ".source" },
  { doc: { passthroughs: ["extractedReferences"] } },
);
